import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# CSV file generated by the benchmarking script
CSV_FILE = "STREAM/stream_single_pair_affinity.csv"

# --- Read data ---
df = pd.read_csv(CSV_FILE)

# Extract columns
threads = df['threads'].to_numpy()
perf_high = df['perf_high_affinity'].to_numpy()
perf_low = df['perf_low_affinity'].to_numpy()

# --- Plot performance vs threads ---
plt.figure(figsize=(9, 5))
plt.plot(threads, perf_high, marker='o', linestyle='-', label='High cache affinity')
plt.plot(threads, perf_low,  marker='s', linestyle='--', label='Low cache affinity')

plt.xlabel('Threads')
plt.ylabel('Performance (mbps/sec)')
plt.title('Performance vs Threads — High vs Low Cache Affinity')
plt.xticks(threads)
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()
plt.show()
